name = "wcwd-history"
main = "src/worker.js"
compatibility_date = "2025-12-20"

# Cron: every 15 minutes
[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "HIST"
id = "a1a3ac7eaf344ae7b4f6c989d4249033"
